version: "3.9"

services:
  api:
    build: .
    container_name: devops-fastapi
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:7-alpine"
    container_name: devops-redis
    ports:
      - "6379:6379"   # optional, nur falls du Redis auch von au√üen testen willst
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    restart: unless-stopped

volumes:
  redis_data:
